### ISSUE TITLE
Search: Facets for user-defined metadata (vocabulary based)  

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#159]
See also #120 
Add support for vocabulary facets

![loreduserfacets](https://cloud.githubusercontent.com/assets/125561/8149833/86d125c0-12a0-11e5-8be9-964dd6b09a4e.png)

**Comment by ShawnMilo** [comment]
@Ferdi @noisecapella 

It appears that it's possible for a `LearningResource` to have multiple terms for the same vocabulary. Is this so?

I know that in practice some shouldn't, such as difficulty. Right now the taxonomy API doesn't prevent someone from adding, for example, both `easy` and `medium` as terms to the same `LearningResource` under the `difficulty` vocabulary.

Do we plan to support multiple, for example, "learning objectives" per `LearningResource`? If so, we need to add a value to the `Vocabulary` model which indicates whether a `LearningResource` may have more than one term from its choices.

This has immediate implications for search, because it determines how indexes will have to be built and will also complicate filtering. Right now, all faceted search is based on the fact that each `LearningResource` can have one (and only one) course, run, and item type. Supporting multiple adds complexity.

**Comment by pdpinch** [comment]
Excellent question. You're right that learning outcomes will need to support multiple values. I'm glad you caught this now. 

Is it reasonable to treat all user-defined taxonomies as if they can support multiple values, and rely on the users to behave? Or do you think that will end up being a performance hit?

**Comment by Ferdi** [comment]
@ShawnMilo thanks for looking into this.  

Ideally, users (e.g. repo admins) would decide how their vocabularies should be used.  For example,  a vocabulary called "topic" would work like "free tagging" - curators can tag a learning resource with one ore more "topic" terms.  That woudn't be the case for "difficulty" vocabulary.

**Comment by ShawnMilo** [comment]
@Ferdi @pdpinch 

Based on your comments, we need to support multiple. I'll do that for the faceted search. This leaves the temporary possibility that someone tags the "difficulty" of a `LearningResource` as easy and hard at the same time, but that's an orthogonal issue so it won't block me. I'll open an issue for that.

**Comment by ShawnMilo** [comment]
@Ferdi @pdpinch:

I'd like to handle #155 as part of this branch. Deploying the taxonomy search without this index trigger doesn't make sense. It should just requiring hooking up an [m2m-changed](https://docs.djangoproject.com/en/1.8/ref/signals/#m2m-changed) signal.

Any objections?

**Comment by Ferdi** [comment]
Go for it
- Sent from my phone

**Comment by ShawnMilo** [comment]
Thanks. #155 has been closed, with a note about this issue.

**Comment by pdpinch** [comment]
Closed by #203
