### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#16]
- [x] Allow users to authenticate using MIT certificate authentication via CAS
- [x] MIT auth should be pluggable , easily enabled / disabled in any LORE instance.

**Comment by carsongee** [comment]
Do we want any attributes to come from CAS? By default, you get nothing but the username, no e-mail, name, etc. We can add some of those depending on the client we use, but chances are that we are going to have to submit some patches to it to make it 1.8 compatible.  We can even pull in groups from the CAS server as well, but I kind of assume we don't want this to provide authz

**Comment by Ferdi** [comment]
I would keep it simple for now. Does getting the username means we get the e-mail too, as username@mit.edu ?

**Comment by carsongee** [comment]
The code won't store that, and due to collaborator accounts, that won't hold true.  For example, if you make a jim@example.com collaborator account the username will be jim_1@touchstonenetwork.net assuming he is the first jim.  Similarly with google accounts (if we allow that), we wouldn't get that either.  That said, the CAS server can provide that information, we just have to write some code to retrieve and extract it properly from the SAML.
