### ISSUE TITLE
Export failing

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#172]
@ShawnMilo or @giocalitri ?

```
Internal Server Error: /learningresources/1/
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./ui/views.py", line 244, in export
    get_resource(resource_id, request.user.id).content_xml,
AttributeError: type object 'HttpResponseForbidden' has no attribute 'content_xml'
```

**Comment by ShawnMilo** [comment]
This is because `get_resource` in `learningresources/api` returns a `LearningResource`
if it can, or `HttpResponseForbidden` if the user has no access. It could also
raise a 404 directly.

This should be fixed; an API function shouldn't return HTTP response objects. I'm going
to change it to return a `LearningResource` or `None`, and let the view return a
404 if it's not found. This is inline with not wanting to leak information by returning
a 403 or 404 based on permissions.
