### ISSUE TITLE
Asynchronous Course Import

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#28]
As a user, I would like to not have my course imports timeout when I either have a slow Internet connection, a large course, or a bit of both.  Dependent on #4

**Comment by pdpinch** [comment]
@ShawnMilo asked: 

> What do you prefer we use for this? rq? Celery? Something else? I'm asking you because I assume whatever we'll use, you'll have preference for the type and backend to add to the infrastructure.

**Comment by carsongee** [comment]
I figured celery with a DB backend to save on external resource dependencies, until we need to something more dedicated, that way we could keep the result store in SQL and be more flexible on the message broken. All that said, this is just from past experience and what we've used here already, I'm always interested in trying something different.

**Comment by ShawnMilo** [comment]
Are we planning to have Redis, one way or another? I like using it for sessions and caching, due to its auto-expiration and easy interface. If so, I really like [rq](http://python-rq.org/). It doesn't have the equivalent of Celery's `periodic_task`, so if we don't need a "cron" then it's simpler.

**Comment by pdpinch** [comment]
@Ferdi can you weigh in on rq vs. celery? rq adds a dependency on redis, celery gives us more options (like memcached). edX uses celery, so the rest of the team has a little more experience with it.

**Comment by Ferdi** [comment]
Either it's fine with me.

**Comment by ShawnMilo** [comment]
@carsongee: No rush, but at some point I'll want to know what I should do regarding running Celery for tox and Heroku. Are we going to use [supervisor](https://pypi.python.org/pypi/supervisor)? Can we run multiple blocking commands? I'll make something work for local testing, but I'm guessing you already have a preferred way of doing this in production.

**Comment by ShawnMilo** [comment]
Regarding using the database backend to reduce dependencies:

The [Celery documentation](http://celery.readthedocs.org/en/latest/getting-started/brokers/django.html) states that:

> The Django database transport is in need of improvements in many areas and there are several open bugs. 

Using it also requires installing `django-celery`, which is otherwise deprecated since Django support is built in to Celery now.

The [supported brokers](http://celery.readthedocs.org/en/latest/getting-started/brokers/index.html) are Redis and RabbitMQ, so I'm going to use a Redis container using the official `redis` image on DockerHub for now. This can be changed easily later if we decide to go another way, but it'll keep things moving and seems like the least amount of overhead.
