### ISSUE TITLE
Adding a vocabulary with the same name returns a generic error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#286]
As a curator, when I create a vocabulary with a name conflict, I should get a specific error, perhaps 

> A Vocabulary named <name> already exists. Please choose a different name"

instead of the generic

> There was a problem adding the Vocabulary`

**Comment by noisecapella** [comment]
#302 fixes the case for a name conflict where the description exists, but if they leave out the description the generic message returns. This is because the validation sometimes stops at the first set of errors and it reports only the missing field.

We might want to build some parser for these validation error messages, maybe something that handles only what we know and uses a generic error message for any surprises. Thoughts?
