### ISSUE TITLE
"Learning Objects" app

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#3]
Is the core component responsible for defining, storing, managing and providing the relevant APIs for managing learning objects and the repositories they belong to.
- This version should simply implement basic models for  Repository, LearningObject and Course
  (https://goo.gl/gmpedb)
- It will be used by the "import" app to store records parsed from the XML doc.

**Comment by ShawnMilo** [comment]
Django uses integers as primary keys by default. I prefer the use of a uuid4. Is this worth considering for these models? It prevents confusion and conflicts during import, export, and distributed storage.

**Comment by Ferdi** [comment]
I'm not sure about the implications in Django but I like the idea and we need uuid-s - It's currently separate from the primary key https://goo.gl/gmpedb.

**Comment by ShawnMilo** [comment]
In the past, I've subclassed Django's `models.Model` to one that automatically uses UUIDs as the primary key, and automatically stores the date created (`auto_now_add=True`) and the last modified date (`auto_now=True`). Also, a "notes" field about any modifications made by admins, and foreign keys to the user who created and last modified them.

(Then used this model everywhere instead of `models.Model`).

**Comment by carsongee** [comment]
That sounds good for inheriting from a common model with extra fields. A question about the database model, is uuid in the diagram supposed to be equivalent to the OLX "url_name" that is often, but not always, a uuid?  If so, we need to make sure that we don't use that uuid as a PK since there will be duplicates among different courses, and xbundle, for example, will strip those out and replace them with "human readable" IDs.  If it isn't, what is the difference between the loid and the uuid, shouldn't both of them uniquely identify an object?

**Comment by Ferdi** [comment]
Some say it's tricky in Django: http://stackoverflow.com/a/3944247

**Comment by Ferdi** [comment]
@carsongee, in the current diagram uuid is machine generated.

**Comment by Ferdi** [comment]
Some details about the LearningObject schema :

| name | comment |
| --- | --- |
| loid | Primary key ID , numeric |
| cid | Course ID |
| rid | Repository ID |
| type | Learning object type (chapter, sequential, vertical, video, html etc.) |
| uuid | UUID , uniquely identifying a learning object across LORE instances |
| title | learning object title, extracted from xml |
| description | _user_ generated title/description |
| contentxml | the XML content of the learning object |
| pathxml | the xpath of this el in the xml doc (I think module_id here https://goo.gl/LE6Vmn |
| mpath | the materialized path |
| urlpath | the url to get to this learning object ("path" here https://goo.gl/LE6Vmn) |
| parentid | the parent ID of this element |
| copyright | string for now |
| xa_nr_views | nr of student views for this element  (will come from analytics service) |
| xa_nr_attempts | nr of attempts (applies to items of type "problem" only) |
| xa_avg_grade | average grade (applies to items of type "problem" only) |
| xa_histogram_grade | histogram of grades  (json type ?) |

**Comment by ghost** [comment]
I'm changing some of the field names:
https://gist.github.com/trski/6ea8c8afb4f783c71b42
Just included some '_' for readability for the python variables and changed 'when' to 'date' so we know the field is a date type.

**Comment by Ferdi** [comment]
:+1:

**Comment by pdpinch** [comment]
Have you pushed anything yet?

**Comment by pdpinch** [comment]
I believe this was closed by #10. @Ferdi are you OK with that?

**Comment by Ferdi** [comment]
I think it's good for now. We can always open new issues for improvements / fixes.
