### ISSUE TITLE
Upgrade haystack to 2.4.0 and new generic_view views

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#329]
http://django-haystack.readthedocs.org/en/latest/views_and_forms.html#upgrading

**Comment by pdpinch** [comment]
@carsongee was this closed by #400 ?

**Comment by carsongee** [comment]
Nope, we haven't actually changed the base class we are using to a non-deprecated one.

**Comment by pdpinch** [comment]
Discovery only for now.

**Comment by ShawnMilo** [comment]
Why are we considering doing this? Are there features we want, are the security concerns with the current version, or do we just generally want to keep up-to-date with our dependencies so we don't end up with a major incompatible upgrade later?

**Comment by ShawnMilo** [comment]
I see Haystack was already upgraded to the latest (2.4.0). So this ticket is just for moving away from a deprecated view form as recommended in the Haystack documentation. So, super-non-urgent, but nice-to-have and shouldn't take long.

**Comment by ShawnMilo** [comment]
I made the required changes and then spent way too much time tracing through the Haystack and Django code trying to figure out why it kept breaking.

It turns out that Haystack 2.40 is simply [broken](https://github.com/django-haystack/django-haystack/issues/1159), at least if you're using facets. There's a [PR](https://github.com/django-haystack/django-haystack/pull/1149) for it, but no action since March.

I manually copied the changes from the PR locally and got past my first error, but then ran into another one. In both cases, there are statements calling attributes that don't exist on Haystack's own classes. The ball has been _seriously_ dropped on the Haystack end.

**Comment by carsongee** [comment]
:facepunch: :(

**Comment by pdpinch** [comment]
@ShawnMilo Shall we close this issue?

**Comment by ShawnMilo** [comment]
I'm in favor of it, especially considering #516. Are there any objections from your or  @carsongee (since he opened the ticket)?

**Comment by carsongee** [comment]
no objections, I guess my face punch sad face wasn't explicit enough ;)
