### ISSUE TITLE
Collapse repository management buttons into a drop-down menu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#418]
To conserve screen real estate, and to group repository management functions, the repository management buttons should all be part of one "admin" menu. The following buttons should go into the menu (preserving their existing permissions)
- Manage Taxonomies
- Manage Members
- Import Analytics
- Index Resources

**Comment by pdpinch** [comment]
@Ferdi is this what you had in mind?

Is the wording on the menu options correct? (would "re-import analytics" and "re-index resources" be better?)

**Comment by pdpinch** [comment]
There is currently no button for "index resources" but there is a management command that can be wired in. I'm not sure yet about "import analytics"

**Comment by amir-qayyum-khan** [comment]
In the up coming PR I am going to move 4 links **Manage Taxonomies, Manage Members, Import Analytics, Index Resources** on the top of repository page (Learning resource page) to the menu that contains **Logout**. So menu on top will become 
- User name + settings icon instead of arrow down
- (Home icon) Index Resources
- (Icon) Manage Taxonomies
- (Icon) Import Analytics
- (Icon) Manage Members
- (Icon) Logout

For this purpose i am going make a change in repository_base file.
I will create repository menu as react component. Will mange all permissions there. (Not sure abt that)

@pdpinch @Ferdi  Am I on same page on this

**Comment by pdpinch** [comment]
@Ferdi this was merged and it's on lore-ci. Can you confirm this is what you wanted?

Kind of looks like this:

![actions](https://cloud.githubusercontent.com/assets/10431250/9168846/bac45a06-3f72-11e5-934c-ef71731f9f79.png)

**Comment by Ferdi** [comment]
Actually, that's not what's I had in mind.

**Comment by pdpinch** [comment]
Let's revert this to use the original horizontal list, but make it responsive so the list collapses when the viewport is shrunk.

**Comment by pdpinch** [comment]
This has been reverted in #539 

We'll reopen this when we have more buttons & a need for a menu.
