### ISSUE TITLE
Importing duplicate courses into a single repo

### ISSUE THREAD

**Issue by tssheth** [mitodl/lore#449]
I was able to import the same course into a lore repo twice.  

![screen shot 2015-07-30 at 4 39 14 pm](https://cloud.githubusercontent.com/assets/8117756/8994598/7a3a48ec-36da-11e5-9385-de39d45771fa.png)

8.MechCx:
https://github.mit.edu/edX-Archives/edX-Archive-8.MechCx-1T2015
Lore Repo:
https://lore-ci.herokuapp.com/repositories/tej-test/

**Comment by pdpinch** [comment]
@carsongee @bdero can you guys take a look at the database for the tej-test repo and see if there are indeed two copies of the same course?

I'm wondering if this might be a race condition, where Tej uploaded a 2nd time before the first was done.

**Comment by pdpinch** [comment]
Need to reproduce.

**Comment by tssheth** [comment]
I cannot seem to reproduce this case with smaller courses that import quickly. I'm guessing this is a race condition as @pdpinch mentioned above.

**Comment by ShawnMilo** [comment]
Based on the [atomic decorator](https://github.com/mitodl/lore/blob/master/learningresources/api.py#L44) and the fact that the course is imported first, this shouldn't be possible.

Also, after taking another look at the screenshot above, the `models.Course` was not in fact imported twice, or it would appear twice under the "Course." header with the same name, and the filtering as shown couldn't possibly contain both "course learning resources." The `models.LearningResource` with the "type" of "course" _was_ evidently duplicated. This could possibly be due to a zombie Celery worker or something else, but is plausible.

So, fortunately, the ticket is actually misstating the problem.

**Comment by ShawnMilo** [comment]
Follow-up for clarification: The same course was _not_ imported twice into the same repository. However, the same LearningResource was imported into the same course -- an important distinction.

**Comment by tssheth** [comment]
I could not reproduce this with a larger course either (6.341x).  @ShawnMilo Could the same LearningResource have been imported twice due to problems caused by https://github.com/mitodl/lore/issues/448?  The duplicate LearningResource was found when only the course item was displaying after a course was imported.

**Comment by pdpinch** [comment]
I think #766 will prevent this from happening again.
