### ISSUE TITLE
API for deleting a course

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#469]
As a tester, I'd like to be able to delete courses from a repository. Curators may also wish to do this.
- [ ] Create API for deleting courses.
  - [ ] This is presumably a cascading delete.
  - [ ] permissions should be the same as for import: administrators and curators
  - [ ] need to delete static files as well

---

A privileged LORE user (administrator, curator?) should be able to delete learning resources from a repository.

**Questions:**
1. What user roles can perform this action?
2. How will the UI support this feature?
3. Is implementing it as web service API sufficient initially?
4. Do deletes cascade?  That is, if a course is deleted, are all its learningresources also deleted?

@pdpinch @carsongee

**Comment by pwilkins** [comment]
Consider that deleting a course might be an entirely different use case than deleting the learning resources of a course.  I find deleting a course much more useful than deleting individual learning resources.

**Comment by pdpinch** [comment]
In discussing with @Ferdi we're going to focus on deleting courses with this issue.

**Comment by ShawnMilo** [comment]
It's not much more work to implement create, update, and delete together instead of just delete.

Currently it doesn't make sense to allow creation, since the only useful way to create a course is to import it, and creating it manually would prevent the "duplicate" course (with all the LearningResources) from being imported.

Do we want to allow updating, like the course number? Hypothetically, someone could import a hand-edited course with typos. This would require re-indexing all LearningResources after course update, because there's currently no signal to trigger that, but that's easy to do.

The only place where it would be immediately useful is in our own unit tests, where we do create courses.

So, take-away questions:
- Do we want to allow course creation via the API?
- Do we want to allow course updating via the API?

Note that if we do only add delete functionality, it shouldn't be much work to tack on update or delete later.
