### ISSUE TITLE
Export panel title's export count is out of sync with rest of page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#471]
If you have three exports and you go to the export panel you will see 'Export (3)' in the side. However if you click an export link and then look at the export panel again this number doesn't update.

**Comment by pwilkins** [comment]
So, for clarity, we're specifying that the `Export` button count is the number of LRs that will be written to the export file, not the number of LRs in the Export Panel list.

**Comment by pdpinch** [comment]
If this is implemented in react, why isn't it working already?

**Comment by amir-qayyum-khan** [comment]
Hi @pdpinch,

Because heading on export panel is not controlled via react, It depends on `exports` array, which is coming  from server (in the dict inside view). So options we have are 
- Page needs to be refreshed because `exports` is change on server,
-  We need to make heading a react component which updates it self from server.

##### See references
- https://github.com/mitodl/lore/blob/master/ui/views.py#L253
- https://github.com/mitodl/lore/blob/master/ui/templates/includes/exports_panel.html#L7

**Comment by pdpinch** [comment]
Thanks Amir. That answers my earlier question. 

React would be the consistent way to do this, but it seems like a lot of work. Did George touch this at all in #474 ?

What about updating the count with javascript when the user unchecks items in the form?

**Comment by amir-qayyum-khan** [comment]
##### Answer to your first question is:

No George just convert export button into react component because it is part of learning resource listing. The scope of his PR only includes listing.
**Please see**
https://github.com/mitodl/lore/pull/474/files#diff-35881df8bdedc9017ef7e2a1ea29cd48R39

##### Second:

 Yes we can do it via javascript, but only for now . When George's PR will merge then we will need to change this code accordingly. Means it is short term solution.

But if you want I can build a react component for this heading?

**Comment by pdpinch** [comment]
Can you do a PR to George's branch that creates the react component for the heading?

**Comment by amir-qayyum-khan** [comment]
Do not need to change Georges PR, because this problem is out of its scope. I can create new PR on current master and create a react component on it.

**Comment by pdpinch** [comment]
Ok, let's go with a react solution then.

**Comment by amir-qayyum-khan** [comment]
Sorry there was misunderstanding , i need to create this PR on top of George work. Because of changes he made in listing.js (As discussed on chat)

Thanks
