### ISSUE TITLE
Sort doesn't appear to be stable

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#511]
As a curator, I need to be able to save metadata to resources and have the search results stay stable. Currently, it appears that the index is updated every time metadata is saved, which upsets the order of the search results. 

It's not clear if this is due to a bug in the sort widget, or if it is due to sorting on fields that are unpopulated (i.e. number of views).

**Comment by ShawnMilo** [comment]
What counts are you seeing for the xanalytics field (views, attempts, and average grade)? If they're all zero, then that's why. Sorting is on one of those fields, and if they're all zero then the sorting is essentially random. If that's the case, then the management command added in #475 could be run to resolve the problem on a course-by-course basis.

**Comment by pdpinch** [comment]
Random would be okay, as long as it was the same random. 

Does that mean if two learning resources have the same number of views (say, 100) their order will be non-deterministic?

**Comment by ShawnMilo** [comment]
I haven't tested it, but that's my first guess. It depends on how Elasticsearch works. I'll mess with it a bit and find out.
