### ISSUE TITLE
Learning resource panel should not load all tabs content

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#770]
Right now when the user opens the panel, there are 4 ajax requests to load the content of all the tabs.

Instead we should load only the content of the visible tab and load the others only if the tab become visible.

**Comment by jamiefolsom** [comment]
Uncertain that this is related (although @noisecapella thinks so, which is good enough for me). I am seeing my browser window hang completely when if I try to edit the first learning resource, which is the whole course.

Steps to reproduce:
1. Load the listing page
2. Click the first resource (eg in this screenshot, the "Missing Title" resource at top): ![screenshot 2015-10-22 15 56 02](https://cloud.githubusercontent.com/assets/882377/10676622/784e917c-78d5-11e5-8c39-c58b1aff3f00.png)
3. Click out of the panel to dismiss it
4. Entire UI is locked up (if not yet, repeat 1-3 once or twice, and it will be).

@noisecapella thinks this is due to the first resource being the whole course, which contains a very large XML file.

**Comment by jamiefolsom** [comment]
@giocalitri see if you can reproduce this issue. As @pwilkins says: "It's a lu-lu" (sp?) cc @pdpinch

**Comment by noisecapella** [comment]
I can consistently reproduce that with Chrome, Firefox seems to avoid this problem. I feel like Chrome isn't liking the huge content_xml string in its DOM, at least from a memory use standpoint

**Comment by jamiefolsom** [comment]
Sounds plausible.

**Comment by Ferdi** [comment]
For a quick fix I would exclude the "course" from being rendered as xml. It's not useful info for anyone.

**Comment by pwilkins** [comment]
I see the same result as @noisecapella , I can hang Chrome repeatably, but not Firefox.  Also, it doesn't seem to fail on the same request each time.

**Comment by pwilkins** [comment]
I should add that I'm getting this error on lore-rc, the v0.12.0 release candidate, so a fix is high priority.  @pdpinch
