### ISSUE TITLE
Demo Video for ODL Eng job candidates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#859]
As a software engineer interested in applying for a position at ODL Engineering, I'd like to see a screencast of LORE so I can understand it's basic features and goals.

**Comment by pdpinch** [comment]
What's the status of this?

**Comment by pwilkins** [comment]
It's ready for review.

**Comment by pdpinch** [comment]
Did we ever distribute this?

**Comment by pwilkins** [comment]
No we didn't distribute the video.  
Since it was intended for the Python Meetup we sponsored and we didn't use it, I wasn't sure what the status of it was.  It was supposed to be for developers rather than users, but @giocalitri reviewed it and thought that no developer would watch more than a minute of it since so much context was needed to understand the content.  I agree with him if that indeed is its intended audience.
